"""
DORA Metrics computation module for GitHub data.

This module contains functions to calculate DORA (DevOps Research and Assessment) metrics
from GitHub repository data. It's designed to work with the data collected by GitHubCollector,
but as a separate step in the data pipeline.
"""

from typing import Dict, Any, List, Optional
from datetime import datetime, timedelta
import json
import statistics
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def load_github_data(file_path: str) -> Dict[str, Any]:
    """
    Load GitHub data from a JSON file generated by the GitHubCollector

    Args:
        file_path: Path to the JSON file

    Returns:
        Dictionary containing the GitHub data
    """
    try:
        with open(file_path, "r") as f:
            data = json.load(f)

        logger.info(f"Loaded GitHub data from {file_path}")
        return data
    except Exception as e:
        logger.error(f"Failed to load GitHub data from {file_path}: {str(e)}")
        raise


def calculate_dora_metrics(
    repo_data: Dict[str, Any],
    time_period_days: int = 90,
    output_file: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Calculate DORA metrics summary from repository data

    Args:
        repo_data: Repository data from collect_dora_metrics
        time_period_days: Time period in days to calculate metrics for
        output_file: Optional path to save the metrics to

    Returns:
        Dictionary with DORA metrics summary
    """
    # Calculate cutoff date for metrics
    cutoff_date = datetime.utcnow() - timedelta(days=time_period_days)

    # Get organization name from data
    org_name = repo_data.get("organization", "unknown")

    summary = {
        "organization": org_name,
        "generated_at": datetime.utcnow().isoformat(),
        "time_period_days": time_period_days,
        "repositories": {},
        "organization_summary": {
            "total_repositories": len(repo_data.get("repositories", {})),
            "deployment_frequency": 0,
            "median_lead_time_hours": 0,
            "change_failure_rate": 0,
            "mttr_hours": 0,  # Mean Time To Recovery
            "total_prs": 0,
            "total_merged_prs": 0,
            "total_deployments": 0,
            "successful_deployments": 0,
            "failed_deployments": 0,
        },
    }

    # Track organization-wide metrics
    all_lead_times = []
    all_recovery_times = []
    org_deployments = 0
    org_successful_deployments = 0
    org_failed_deployments = 0
    org_merged_prs = 0
    org_total_prs = 0

    for repo_name, repo_info in repo_data.get("repositories", {}).items():
        if "error" in repo_info:
            summary["repositories"][repo_name] = {"error": repo_info["error"]}
            continue

        # Extract metrics
        pull_requests = repo_info.get("pullRequests", {}).get("nodes", [])
        deployments = repo_info.get("deployments", {}).get("nodes", [])
        releases = repo_info.get("releases", {}).get("nodes", [])

        # Filter data by cutoff date
        filtered_prs = []
        for pr in pull_requests:
            try:
                pr_date = datetime.fromisoformat(
                    pr.get("createdAt", "").replace("Z", "+00:00")
                )
                if pr_date >= cutoff_date:
                    filtered_prs.append(pr)
            except (ValueError, TypeError):
                continue

        filtered_deployments = []
        for deployment in deployments:
            try:
                deploy_date = datetime.fromisoformat(
                    deployment.get("createdAt", "").replace("Z", "+00:00")
                )
                if deploy_date >= cutoff_date:
                    filtered_deployments.append(deployment)
            except (ValueError, TypeError):
                continue

        # 1. Deployment Frequency by environment
        environments = {}
        for deployment in filtered_deployments:
            env = deployment.get("environment", "unknown")
            if env not in environments:
                environments[env] = {"count": 0, "successful": 0, "failed": 0}
            environments[env]["count"] += 1

            # Determine deployment success
            status = deployment.get("latestStatus", {}).get("state", "").upper()
            if status in ("SUCCESS", "ACTIVE", "IN_PROGRESS"):
                environments[env]["successful"] += 1
                org_successful_deployments += 1
            elif status in (
                "ERROR",
                "FAILURE",
                "INACTIVE",
                "PENDING",
                "QUEUED",
                "WAITING",
            ):
                environments[env]["failed"] += 1
                org_failed_deployments += 1

        deployment_count = len(filtered_deployments)
        org_deployments += deployment_count

        # 2. Lead Time for Changes (time from PR creation to merge)
        lead_times = []
        for pr in filtered_prs:
            if pr.get("state") == "MERGED" and pr.get("mergedAt"):
                created_at = datetime.fromisoformat(
                    pr.get("createdAt", "").replace("Z", "+00:00")
                )
                merged_at = datetime.fromisoformat(
                    pr.get("mergedAt", "").replace("Z", "+00:00")
                )
                lead_time_hours = (merged_at - created_at).total_seconds() / 3600
                lead_times.append(lead_time_hours)
                all_lead_times.append(lead_time_hours)

        # 3. Change Failure Rate
        merged_prs = sum(1 for pr in filtered_prs if pr.get("state") == "MERGED")
        org_merged_prs += merged_prs
        org_total_prs += len(filtered_prs)

        failed_deployments = sum(env["failed"] for env in environments.values())

        # Only calculate failure rate if we have merged PRs
        if merged_prs > 0 and deployment_count > 0:
            change_failure_rate = failed_deployments / deployment_count
        else:
            change_failure_rate = 0

        # 4. Mean Time to Restore Service (MTTR)
        # This requires incident data which might not be directly available
        # Here we estimate from deployment failures to recovery
        recovery_times = []

        # Calculate median, not average to avoid outliers
        median_lead_time = 0
        if lead_times:
            median_lead_time = statistics.median(lead_times)

        # Store metrics
        summary["repositories"][repo_name] = {
            "pr_count": len(filtered_prs),
            "merged_prs": merged_prs,
            "deployment_count": deployment_count,
            "deployment_frequency_per_week": (deployment_count * 7) / time_period_days
            if time_period_days > 0
            else 0,
            "deployments_by_environment": environments,
            "lead_time_for_changes": {
                "min_hours": min(lead_times) if lead_times else 0,
                "max_hours": max(lead_times) if lead_times else 0,
                "median_hours": median_lead_time,
                "pr_count_with_timing": len(lead_times),
            },
            "change_failure_rate": change_failure_rate,
            "successful_deployments": sum(
                env["successful"] for env in environments.values()
            ),
            "failed_deployments": failed_deployments,
            "releases": len(releases),
        }

    # Calculate organization-wide summaries
    if all_lead_times:
        summary["organization_summary"]["median_lead_time_hours"] = statistics.median(
            all_lead_times
        )

    if all_recovery_times:
        summary["organization_summary"]["mttr_hours"] = statistics.median(
            all_recovery_times
        )

    if org_deployments > 0:
        summary["organization_summary"]["change_failure_rate"] = (
            org_failed_deployments / org_deployments
        )

    summary["organization_summary"]["deployment_frequency"] = org_deployments
    summary["organization_summary"]["successful_deployments"] = (
        org_successful_deployments
    )
    summary["organization_summary"]["failed_deployments"] = org_failed_deployments
    summary["organization_summary"]["total_prs"] = org_total_prs
    summary["organization_summary"]["total_merged_prs"] = org_merged_prs

    # Calculate deployment frequency per week
    if time_period_days > 0:
        summary["organization_summary"]["deployment_frequency_per_week"] = (
            org_deployments * 7
        ) / time_period_days

    # Save the metrics to a file if requested
    if output_file:
        try:
            output_path = Path(output_file)
            output_path.parent.mkdir(parents=True, exist_ok=True)

            with open(output_path, "w") as f:
                json.dump(summary, f, indent=2)

            logger.info(f"Saved DORA metrics to {output_file}")
        except Exception as e:
            logger.error(f"Failed to save DORA metrics to {output_file}: {str(e)}")

    return summary


def get_four_key_metrics(summary: Dict[str, Any]) -> Dict[str, Any]:
    """
    Extract the four key DORA metrics from the summary for easier access

    Args:
        summary: The DORA metrics summary

    Returns:
        Dictionary with the four key metrics
    """
    org_summary = summary.get("organization_summary", {})

    return {
        "deployment_frequency_per_week": org_summary.get(
            "deployment_frequency_per_week", 0
        ),
        "lead_time_for_changes_hours": org_summary.get("median_lead_time_hours", 0),
        "change_failure_rate": org_summary.get("change_failure_rate", 0),
        "mean_time_to_recover_hours": org_summary.get("mttr_hours", 0),
    }


def classify_performance_level(metrics: Dict[str, Any]) -> Dict[str, str]:
    """
    Classify the performance level of each DORA metric according to research benchmarks

    Args:
        metrics: The four key metrics

    Returns:
        Dictionary with performance level for each metric
    """
    # Classification logic based on DORA research
    # https://cloud.google.com/blog/products/devops-sre/using-the-four-keys-to-measure-your-devops-performance

    # Deployment Frequency
    df = metrics.get("deployment_frequency_per_week", 0)
    if df >= 7:  # Multiple deploys per day
        df_level = "Elite"
    elif df >= 1:  # Between once per day and once per week
        df_level = "High"
    elif df >= 0.25:  # Between once per week and once per month
        df_level = "Medium"
    else:  # Less than once per month
        df_level = "Low"

    # Lead Time for Changes
    lt = metrics.get("lead_time_for_changes_hours", 0)
    if lt <= 24:  # Less than one day
        lt_level = "Elite"
    elif lt <= 168:  # Less than one week
        lt_level = "High"
    elif lt <= 720:  # Less than one month
        lt_level = "Medium"
    else:  # More than one month
        lt_level = "Low"

    # Change Failure Rate
    cfr = metrics.get("change_failure_rate", 0) * 100  # Convert to percentage
    if cfr <= 15:
        cfr_level = "Elite"
    elif cfr <= 30:
        cfr_level = "High"
    elif cfr <= 45:
        cfr_level = "Medium"
    else:
        cfr_level = "Low"

    # Time to Restore Service
    mttr = metrics.get("mean_time_to_recover_hours", 0)
    if mttr <= 1:  # Less than one hour
        mttr_level = "Elite"
    elif mttr <= 24:  # Less than one day
        mttr_level = "High"
    elif mttr <= 168:  # Less than one week
        mttr_level = "Medium"
    else:  # More than one week
        mttr_level = "Low"

    return {
        "deployment_frequency": df_level,
        "lead_time_for_changes": lt_level,
        "change_failure_rate": cfr_level,
        "mean_time_to_recover": mttr_level,
    }


def main(input_file: str, output_file: str = None, time_period_days: int = 90):
    """
    Command-line interface to calculate DORA metrics from a GitHub data file

    Args:
        input_file: Path to the GitHub data JSON file
        output_file: Path to save the metrics to
        time_period_days: Time period in days to calculate metrics for
    """
    try:
        # Load the data
        data = load_github_data(input_file)

        # Calculate metrics
        metrics = calculate_dora_metrics(data, time_period_days, output_file)

        # Extract and print the four key metrics
        four_keys = get_four_key_metrics(metrics)
        performance = classify_performance_level(four_keys)

        # Print summary
        print("\nDORA Metrics Summary:")
        print(f"Organization: {metrics.get('organization', 'unknown')}")
        print(f"Generated at: {metrics.get('generated_at', 'unknown')}")
        print(f"Time period: {time_period_days} days")
        print(
            f"Total repositories: {metrics.get('organization_summary', {}).get('total_repositories', 0)}"
        )

        print("\nFour Key Metrics:")
        print(
            f"1. Deployment Frequency: {four_keys['deployment_frequency_per_week']:.2f} per week ({performance['deployment_frequency']})"
        )
        print(
            f"2. Lead Time for Changes: {four_keys['lead_time_for_changes_hours']:.2f} hours ({performance['lead_time_for_changes']})"
        )
        print(
            f"3. Change Failure Rate: {four_keys['change_failure_rate']*100:.2f}% ({performance['change_failure_rate']})"
        )
        print(
            f"4. Mean Time to Recover: {four_keys['mean_time_to_recover_hours']:.2f} hours ({performance['mean_time_to_recover']})"
        )

        if output_file:
            print(f"\nDetailed metrics saved to: {output_file}")

    except Exception as e:
        logger.error(f"Error calculating DORA metrics: {str(e)}")
        raise


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Calculate DORA metrics from GitHub data"
    )
    parser.add_argument("input_file", help="Path to the GitHub data JSON file")
    parser.add_argument("--output", "-o", help="Path to save the metrics to")
    parser.add_argument(
        "--days",
        "-d",
        type=int,
        default=90,
        help="Time period in days to calculate metrics for",
    )

    args = parser.parse_args()
    main(args.input_file, args.output, args.days)
