version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack gateway to AWS services
      - "4571:4571"
    environment:
      - SERVICES=s3,redshift,lambda,kinesis # Add other AWS services as needed
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data # Optional persistent storage
    volumes:
      - "./localstack:/tmp/localstack" # Optional volume for data persistence

  jupyter:
    build: .
    container_name: data_pipeline_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    environment:
      - SPARK_HOME=/opt/spark
    depends_on:
      - localstack
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
